name: deploy-notes

# Only run this when the main branch changes
on:
  push:
    branches:
    - main

# This job installs dependencies, build the notes, and pushes it to `gh-pages`
jobs:
  deploy-notes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Install dependencies
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - name: Upgrade pip
      run: python3 -m pip install --upgrade pip setuptools wheel

    # - name: Cache dependencies
    #   uses: actions/cache@v3.2.0
    #   with:
    #     path: ~/.cache/pip
    #     key: ${{ runner.os }}-pip-${{ hashFiles('**/freeze.txt') }}
    #     restore-keys: ${{ runner.os }}-pip-
    
    # - name: Install dependencies
    #   run: |
    #      python3 -m pip install --no-deps -r freeze.txt
    - name: Install dependencies
      run: |
         python3 -m pip install -r requirements.txt

    # Build the notes
    - name: Build the notes
      shell: bash -l {0}
      run: |
        jupyter-book build notes -vv

    # Push the notes's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.9.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./notes/_build/html
